name: e_commerce
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  get: ^4.6.6
  flutter_lints: ^3.0.2
  http: any
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.1
  flutter_bloc: ^8.1.6
  image_loader_flutter: ^0.0.3
  bloc_test: ^9.1.7
  get_it: ^7.7.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  octo_image: ^2.1.0
  http_parser: ^4.0.2
  onboarding: ^4.0.2
  flutter_native_splash: ^2.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.5
  build_runner: ^2.1.2
  mocktail: ^1.0.4

  


flutter:


  uses-material-design: true


  assets:
    - asset/shoes.jpeg
    - asset/fira.jpg
    - asset/image-load-failed-128.png
    - asset/json/dummy_data.json
    - asset/onboard.png
    


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
